In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [5]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [6]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [8]:
s1 + s2 #indekslar bo'yicha qo'shish, yo'q indekslarga NaN qaytaradi

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [9]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3), columns = list('bcd'), index = ['Olma', 'Anor', 'Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns = list('abc'), index = ['Olma', 'Anor', 'Qovun', 'Anjir'])

In [10]:
df1

        b    c    d
Olma  0.0  1.0  2.0
Anor  3.0  4.0  5.0
Uzum  6.0  7.0  8.0

In [11]:
df2

         a     b     c
Olma   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Qovun  6.0   7.0   8.0
Anjir  9.0  10.0  11.0

In [13]:
df1 + df2 # mos qator va mos ustunlardagi qiymatlarni qo'shadi

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [16]:
df1.add(df2, fill_value = 0) #add mavjud bo'lmagan qiymatlarga o'zimiz qiymat berishimiz uchun qulay.

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [17]:
df2.sub(df1, fill_value = 0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [19]:
df1.rsub(df2, fill_value = 0) #rsub o'ngdan chapga ayirish yani df2 - df1

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [23]:
df = pd.DataFrame(np.arange(1, 13.).reshape(3,4), index = list('abc'), columns = ['Olma', 'Anor', 'Qovun', 'Anjir'])
obj = pd.Series([1,1,2,2], index = df.columns)

In [24]:
df

   Olma  Anor  Qovun  Anjir
a   1.0   2.0    3.0    4.0
b   5.0   6.0    7.0    8.0
c   9.0  10.0   11.0   12.0

In [25]:
obj

Olma     1
Anor     1
Qovun    2
Anjir    2
dtype: int64

In [26]:
df + obj #Series obyektini ustunlari DataFrame qatorlari mos qiymatlari bo'yicha qo'shadi

   Olma  Anor  Qovun  Anjir
a   2.0   3.0    5.0    6.0
b   6.0   7.0    9.0   10.0
c  10.0  11.0   13.0   14.0

In [27]:
obj = pd.Series([2,3,1], index = ['Olma', 'Uzum', 'Qovun'])

In [28]:
obj

Olma     2
Uzum     3
Qovun    1
dtype: int64

In [29]:
df.sub(obj)

   Anjir  Anor  Olma  Qovun  Uzum
a    NaN   NaN  -1.0    2.0   NaN
b    NaN   NaN   3.0    6.0   NaN
c    NaN   NaN   7.0   10.0   NaN

In [34]:
obj['Olma'] #'Olma' ning qiymati 2 ga teng

np.int64(2)

In [35]:
df + obj['Olma']

   Olma  Anor  Qovun  Anjir
a   3.0   4.0    5.0    6.0
b   7.0   8.0    9.0   10.0
c  11.0  12.0   13.0   14.0