In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = {
    'Yil' : [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni' : [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp' : [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]
}

In [5]:
df = pd.DataFrame(data) # lug'atda datafreym yaratish

In [6]:
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [7]:
df.head() #yuqoridagi 5 ta qiymatni qaytaradi

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [8]:
df.shape # datafreymning hajmini ko'rsatadi

(8, 3)

In [11]:
df = pd.DataFrame(data, columns = ['Yil', 'Temp', 'Aholi soni']) #ustunlar ketma ketligini yozish

In [13]:
df.head()

    Yil  Temp  Aholi soni
0  2021  1.54        33.9
1  2020  1.48        33.5
2  2019  1.56        32.9
3  2018  1.62        32.5
4  2017  1.65        31.9

In [14]:
df = pd.DataFrame(data, columns = ['Yil', 'Temp', 'Aholi soni', 'YAIM']) #datafreym ustunlari ichida YAIM degan ustun yoq, NaN qaytaradi

In [16]:
df.head()

    Yil  Temp  Aholi soni YAIM
0  2021  1.54        33.9  NaN
1  2020  1.48        33.5  NaN
2  2019  1.56        32.9  NaN
3  2018  1.62        32.5  NaN
4  2017  1.65        31.9  NaN

In [17]:
df = pd.DataFrame(data, columns = ['Yil', 'Temp', 'Aholi soni', 'YAIM'], index = [21, 20, 19, 18, 17,16, 15, 10])

In [18]:
df

     Yil  Temp  Aholi soni YAIM
21  2021  1.54        33.9  NaN
20  2020  1.48        33.5  NaN
19  2019  1.56        32.9  NaN
18  2018  1.62        32.5  NaN
17  2017  1.65        31.9  NaN
16  2016  1.66        31.4  NaN
15  2015  1.64        30.9  NaN
10  2010  1.53        28.5  NaN

In [20]:
df['Aholi soni'] #ustunlarni alohida qaytarish Series  malumotlar qaytaradi

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [21]:
df.Temp #ustunlarni alohida qaytarish Series  malumotlar qaytaradi

21    1.54
20    1.48
19    1.56
18    1.62
17    1.65
16    1.66
15    1.64
10    1.53
Name: Temp, dtype: float64

In [24]:
df.YAIM = 0 # ustun qiymatlarini o'zgartirish NaN --> 0

In [25]:
df

     Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9     0
20  2020  1.48        33.5     0
19  2019  1.56        32.9     0
18  2018  1.62        32.5     0
17  2017  1.65        31.9     0
16  2016  1.66        31.4     0
15  2015  1.64        30.9     0
10  2010  1.53        28.5     0

In [26]:
val = pd.Series([1700, 1650, 1300], index = [21, 20, 10])

In [29]:
df.YAIM = val #mos indekslarni qiymatini o'zgartiradi

In [30]:
df

     Yil  Temp  Aholi soni    YAIM
21  2021  1.54        33.9  1700.0
20  2020  1.48        33.5  1650.0
19  2019  1.56        32.9     NaN
18  2018  1.62        32.5     NaN
17  2017  1.65        31.9     NaN
16  2016  1.66        31.4     NaN
15  2015  1.64        30.9     NaN
10  2010  1.53        28.5  1300.0

In [33]:
val = [1700, 1650, 1600, 1500, 1450, 1400, 1300, 1250]
df.YAIM = val # YAIM ustunidagi barcha qiymatlarni o'zgartirish

In [39]:
df.head()

     Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9  1700
20  2020  1.48        33.5  1650
19  2019  1.56        32.9  1600
18  2018  1.62        32.5  1500
17  2017  1.65        31.9  1450

In [35]:
df['1500+'] = df.YAIM > 1500 # 1500+ degan yangi ustun qo'shib va shu ustunga YAIM qiymati 
#1500 dan katta bo'lganiga True qaytaradi

In [36]:
df

     Yil  Temp  Aholi soni  YAIM  1500+
21  2021  1.54        33.9  1700   True
20  2020  1.48        33.5  1650   True
19  2019  1.56        32.9  1600   True
18  2018  1.62        32.5  1500  False
17  2017  1.65        31.9  1450  False
16  2016  1.66        31.4  1400  False
15  2015  1.64        30.9  1300  False
10  2010  1.53        28.5  1250  False

In [37]:
del df['1500+'] # 1500+ ustunni o'chirib yuborish

In [38]:
df

     Yil  Temp  Aholi soni  YAIM
21  2021  1.54        33.9  1700
20  2020  1.48        33.5  1650
19  2019  1.56        32.9  1600
18  2018  1.62        32.5  1500
17  2017  1.65        31.9  1450
16  2016  1.66        31.4  1400
15  2015  1.64        30.9  1300
10  2010  1.53        28.5  1250