In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = {
    'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = pd.DataFrame(data)

In [5]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [6]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]

In [7]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [8]:
data = df['Aholi soni']
data

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [9]:
data[21] # numpy float qaytaradi

np.float64(33.9)

In [10]:
data[[21]] # series qaytaradi

21    33.9
Name: Aholi soni, dtype: float64

In [11]:
type(data)

pandas.core.series.Series

In [12]:
data[0:4] #birinchi 4 ta indeksdagi qiymatlarni qaytaradi

21    33.9
20    33.5
19    32.9
18    32.5
Name: Aholi soni, dtype: float64

In [13]:
data[[21,20,19,18]] #birinchi 4 ta indeksdagi qiymatlarni qaytaradi

21    33.9
20    33.5
19    32.9
18    32.5
Name: Aholi soni, dtype: float64

In [14]:
obj = pd.Series(np.arange(8.), index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [15]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [16]:
obj[['a']]

a    0.0
dtype: float64

In [17]:
obj[0:4]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [18]:
obj['a':'f']

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [19]:
obj[['a','g']]

a    0.0
g    6.0
dtype: float64

In [20]:
obj['a':'c'] = 15 # qiymatlarni o'zgartirish

In [21]:
obj

a    15.0
b    15.0
c    15.0
d     3.0
e     4.0
f     5.0
g     6.0
h     7.0
dtype: float64

In [22]:
obj[obj<15] # qiymati 15 dan kichik bo'lgan qiymatlarni qaytarish

d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [23]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9, 2016:31.4, 2015:30.9}
kz = {2020:18.8, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8, 2015:17.6}
tj = {2020:10.8, 2019:10.5, 2018:10.3, 2017:10.1, 2016:9.8, 2015:9.6}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.2, 2016:6.1, 2015:6.0}
tr = {2020:6.0, 2019:5.4, 2018:5.3, 2017:5.2, 2016:5.1, 2015:5.0}

df = pd.DataFrame({
    'Uzbekistan': uz,
    'Kazakhstan' : kz,
    'Tadjikistan' : tj,
    'Kyrgizistan' : kg,
    'Turkmenistan' : tr
})
df

      Uzbekistan  Kazakhstan  Tadjikistan  Kyrgizistan  Turkmenistan
2020        33.5        18.8         10.8          6.5           6.0
2019        32.9        18.5         10.5          6.4           5.4
2018        32.5        18.3         10.3          6.3           5.3
2017        31.9        18.1         10.1          6.2           5.2
2016        31.4        17.8          9.8          6.1           5.1
2015        30.9        17.6          9.6          6.0           5.0

In [24]:
df['Uzbekistan'] #series qaytaradi

2020    33.5
2019    32.9
2018    32.5
2017    31.9
2016    31.4
2015    30.9
Name: Uzbekistan, dtype: float64

In [26]:
df[['Uzbekistan']] #datafreym qaytaradi

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [28]:
df["Uzbekistan"].to_numpy() #numpy array(massiv) qaytaradi

array([33.5, 32.9, 32.5, 31.9, 31.4, 30.9])

In [29]:
df[['Uzbekistan', 'Turkmenistan']]

      Uzbekistan  Turkmenistan
2020        33.5           6.0
2019        32.9           5.4
2018        32.5           5.3
2017        31.9           5.2
2016        31.4           5.1
2015        30.9           5.0

In [30]:
df[3:] # oxirgi 3 ta qiymatni qaytarish

      Uzbekistan  Kazakhstan  Tadjikistan  Kyrgizistan  Turkmenistan
2017        31.9        18.1         10.1          6.2           5.2
2016        31.4        17.8          9.8          6.1           5.1
2015        30.9        17.6          9.6          6.0           5.0

In [31]:
df>10 # shart bajarilsa True qaytaradi

      Uzbekistan  Kazakhstan  Tadjikistan  Kyrgizistan  Turkmenistan
2020        True        True         True        False         False
2019        True        True         True        False         False
2018        True        True         True        False         False
2017        True        True         True        False         False
2016        True        True        False        False         False
2015        True        True        False        False         False

In [32]:
df>7

      Uzbekistan  Kazakhstan  Tadjikistan  Kyrgizistan  Turkmenistan
2020        True        True         True        False         False
2019        True        True         True        False         False
2018        True        True         True        False         False
2017        True        True         True        False         False
2016        True        True         True        False         False
2015        True        True         True        False         False

In [35]:
df[['Uzbekistan']][df['Uzbekistan']>32] # ayrim qiymatlarni shart berib tekshirish

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [36]:
df2 = df.transpose(copy=True) #shaklini o'zgartirish. copy=True ichidagi malumotlarni ko'chirish

In [37]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tadjikistan   10.8  10.5  10.3  10.1   9.8   9.6
Kyrgizistan    6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.4   5.3   5.2   5.1   5.0

In [38]:
df2[df2[2015]>6]

             2020  2019  2018  2017  2016  2015
Uzbekistan   33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan   18.8  18.5  18.3  18.1  17.8  17.6
Tadjikistan  10.8  10.5  10.3  10.1   9.8   9.6