In [1]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
df = pd.DataFrame(np.random.randn(3,4), index = list('abc'), columns = ['Anor', 'Anjir', 'Qovun', 'Uzum'])

In [7]:
df

       Anor     Anjir     Qovun      Uzum
a  0.443657  1.371272 -1.970888 -0.106043
b  1.242007  0.015330  0.806589 -0.144543
c  0.178189  1.114882  0.570967  0.871117

In [9]:
np.abs(df) # barcha qiymatlarni musbat qaytaradi

       Anor     Anjir     Qovun      Uzum
a  0.443657  1.371272  1.970888  0.106043
b  1.242007  0.015330  0.806589  0.144543
c  0.178189  1.114882  0.570967  0.871117

In [11]:
np.round(df) #barcha qiymatlarni yaxlitlash

   Anor  Anjir  Qovun  Uzum
a   0.0    1.0   -2.0  -0.0
b   1.0    0.0    1.0  -0.0
c   0.0    1.0    1.0   1.0

In [14]:
df.mean() # ustunlar bo'yicha o'rtacha qiymat qytarish

Anor     0.621284
Anjir    0.833828
Qovun   -0.197778
Uzum     0.206843
dtype: float64

In [15]:
df.mean(axis = 1) #qatorlar bo'yicha o'rtacha qiymat qaytarish

a   -0.065500
b    0.479846
c    0.683789
dtype: float64

In [17]:
df.apply(np.abs) # apply orqali funksiya chaqirish

       Anor     Anjir     Qovun      Uzum
a  0.443657  1.371272  1.970888  0.106043
b  1.242007  0.015330  0.806589  0.144543
c  0.178189  1.114882  0.570967  0.871117

In [18]:
df.apply(sum) #ustunlar bo'yicha yig'indini hisoblash

Anor     1.863852
Anjir    2.501485
Qovun   -0.593333
Uzum     0.620530
dtype: float64

In [20]:
df.apply(sum, axis = 1) #qatorlar bo'yicha yig;indini hisoblash

a   -0.262002
b    1.919382
c    2.735154
dtype: float64

In [22]:
df.apply(lambda x: x.max() - x.min())

Anor     1.063818
Anjir    1.355942
Qovun    2.777477
Uzum     1.015660
dtype: float64

In [24]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index = list('abc'), columns = ['Anor', 'Olma', 'Anjir', 'Uzum'])

In [25]:
df

   Anor  Olma  Anjir  Uzum
a     1     2      3     4
b     5     6      7     8
c     9    10     11    12

In [30]:
df.map(lambda x: x*x)

   Anor  Olma  Anjir  Uzum
a     1     4      9    16
b    25    36     49    64
c    81   100    121   144