In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
data = {
    'Uzbekistan' : {2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan' : {2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [8]:
df.index.name = 'Yil' #indeksni nomlash

In [9]:
df

      Uzbekistan  Kazakhstan
Yil
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [10]:
df = pd.DataFrame(data, index = [2021, 2019, 2017]) #malum indeksdagi qiymatlarni qaytaradi

In [11]:
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [12]:
df.T # ustunlar bilan indekslar o'rnini almashtirish

            2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1

In [13]:
df.values #numpydagi array(massiv) qaytaradi

array([[33.9, 18.9],
       [32.9, 18.5],
       [31.9, 18.1]])