In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
data = {
    'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = pd.DataFrame(data)

In [7]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [8]:
df.index = [21, 20, 19, 18,17, 16, 15, 10] #indekslarning qiymatini o'zgartirish

In [9]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [10]:
ind = [21, 20, 19, 18, 17, 16, 15, 10]
ind.sort()

In [11]:
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [12]:
df.reindex(ind) #qayta indekslash, yangi datafreym qaytaradi asl datafreym o'zgarmaydi

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [13]:
df # datafreym o'zgargani yoq

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [14]:
df = df.reindex(ind) # asl datafreymni o'zgartirish

In [15]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [16]:
df.reindex([10,15,20]) #faqatgina berilgan indeksdagi qiymatlarni saqlab qoladi

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
20  2020        33.5  1.48    78.68

In [17]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [18]:
df.reindex(index = range(10,22)) #yangi indeks va qiymatlar qo'shadi kiritilmagan qiymatlarga NaN qaytaradi

       Yil  Aholi soni  Temp  Zichlik
10  2010.0        28.5  1.53    67.03
11     NaN         NaN   NaN      NaN
12     NaN         NaN   NaN      NaN
13     NaN         NaN   NaN      NaN
14     NaN         NaN   NaN      NaN
15  2015.0        30.9  1.64    72.71
16  2016.0        31.4  1.66    73.91
17  2017.0        31.9  1.65    75.13
18  2018.0        32.5  1.62    76.34
19  2019.0        32.9  1.56    77.53
20  2020.0        33.5  1.48    78.68
21  2021.0        33.9  1.54    79.77

In [19]:
df.reindex(index = range(10,22), method = 'nearest') #NaN qiymatlarni eng yaqin qiymatlar bilan almashtirdai

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [20]:
df.reindex(index = range(10,22), method = 'ffill') # bir xil qiymat qo'shadi

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2010        28.5  1.53    67.03
14  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [21]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [22]:
df2 = df.reindex(columns = ['Aholi soni', 'Temp', 'Zichlik']) #Yil degan ustunni olib tashlash

In [23]:
df2.sample() # tasodifiy qiymat qaytaradi

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77

In [24]:
df2.sample(3) # 3 ta tasodifiy qiymat qaytaradi

    Aholi soni  Temp  Zichlik
18        32.5  1.62    76.34
19        32.9  1.56    77.53
16        31.4  1.66    73.91

In [25]:
df.loc[[15,17,18,20],['Aholi soni', 'Temp', 'Zichlik']] #faqat belgilangan indeksdagi qiymalarni qaytaradi

    Aholi soni  Temp  Zichlik
15        30.9  1.64    72.71
17        31.9  1.65    75.13
18        32.5  1.62    76.34
20        33.5  1.48    78.68

In [28]:
df2 = df.drop([10]) # 10 indexni tashlab yuborish
df2

     Yil  Aholi soni  Temp  Zichlik
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [31]:
df.drop([10,15])

     Yil  Aholi soni  Temp  Zichlik
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [35]:
df.drop('Yil', axis = 1) #ustunlarni tashlab yuborish

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
16        31.4  1.66    73.91
17        31.9  1.65    75.13
18        32.5  1.62    76.34
19        32.9  1.56    77.53
20        33.5  1.48    78.68
21        33.9  1.54    79.77

In [39]:
df.drop('Yil', axis = 'columns') #ustunlarni tashlab yuborish

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
16        31.4  1.66    73.91
17        31.9  1.65    75.13
18        32.5  1.62    76.34
19        32.9  1.56    77.53
20        33.5  1.48    78.68
21        33.9  1.54    79.77

In [40]:
df.drop('Yil', axis = 'columns', inplace = True) # asl datafreymni ham o'zgartirish

In [41]:
df

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
16        31.4  1.66    73.91
17        31.9  1.65    75.13
18        32.5  1.62    76.34
19        32.9  1.56    77.53
20        33.5  1.48    78.68
21        33.9  1.54    79.77